feat: Improving fio_zone_throughput_avg_lat benchmark.
westerndigitalcorporation/zbdbench pull request #12
Opened 2022-01-17 12:47 UTC by MaisenbacherD

Refined max_open_zone and queue_depth parameters.
Generating throughput and latency plots for all parameter combinations.
Added plots for latency percentiles.

Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

2022-01-31 15:06 UTC, metaspace requested changes
Looks good, but for a doc update that when to the wrong line :)

2022-01-31 15:06 UTC, metaspace commented on README.md
> +      - BS: 4K, 8K, 14K, 64K, 128K
I think this comment update is wrong. Should not be BS?

2022-02-08 14:49 UTC, MaisenbacherD commented on README.md
> +      - BS: 4K, 8K, 14K, 64K, 128K
You are right. QD has to be updated.

2022-02-09 10:50 UTC, MaisenbacherD commented
After an offline discussion with @metaspace we agreed that `QD: 1, 2, 4, 8, 14, 16, 32, 64` makes more sense. QD 14 is useful because of writes dropping QD > max_open_zones.

2022-02-09 13:42 UTC, merged