Introduce MySQL data collector
westerndigitalcorporation/zbdbench pull request #14
Opened 2022-03-11 11:19 UTC by MaisenbacherD

If the environment file `recipes/docker-compose/.env` exists, the JSON
output files of a benchmark run are collected into the specified MySQL
instance.

A new subcommand can collect JSON output files from old benchmarks runs
into the MySQL instance defined by the environment file.

A simple MySQL instance can be spun up by the provided docker-compose
file.

Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

2022-03-21 09:09 UTC, metaspace requested changes

2022-03-21 09:09 UTC, metaspace commented on README.md
> +docker-compose -f ./recipes/docker-compose/mongodb.yml up
mongodb?

2022-03-22 16:22 UTC, MaisenbacherD commented
Rebased this PR onto main

2022-06-22 11:17 UTC, MaisenbacherD commented
This PR needs some rework: Make use of SQL joins

2023-04-03 13:52 UTC, MaisenbacherD commented
Closing PR as this feature will be reworked and addressed in a new PR.

2023-04-03 13:52 UTC, closed without merging