Path fixes
westerndigitalcorporation/zbdbench pull request #20
Opened 2022-10-11 06:42 UTC by indraneel-m

Cleanup fixes before introducing the spdk support patchset.
- Fix incorrect identification of zoned dev
- Add '--privileged' to default container cmdline
- Fix incorrect output dir path

2022-10-11 08:00 UTC, MaisenbacherD reviewed
Looks good :)
Could you just add a prefixes (e.g. 'fix:', 'feat:', 'refactor:') to each commit message (see https://www.conventionalcommits.org/en/v1.0.0/)?

2022-10-11 11:05 UTC, indraneel-m commented
> Looks good :) Could you just add a prefix (e.g. 'fix:', 'feat:', 'refactor:') to each commit message (see https://www.conventionalcommits.org/en/v1.0.0/)?

Done.

2022-10-11 14:40 UTC, metaspace requested changes
Had a few questions

2022-10-11 14:40 UTC, metaspace commented on benchs/base.py
> +        if zoned_dev:
Why did `is_dev_zoned(path) not work?

2022-10-11 14:40 UTC, metaspace commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
Why do we need to run the container privileged?

2022-10-11 14:46 UTC, MaisenbacherD commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
When we create filesystems within the container we need the privileged flag.

2022-10-11 17:34 UTC, metaspace commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
Is it for `mkfs`? What kind of privilege is it that we need?

2022-10-12 10:50 UTC, MaisenbacherD commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
Yes it is for `mkfs` on volumes. I guess the privilege that we need is disabling 'read-only mounts'.

2022-10-12 11:55 UTC, indraneel-m commented on benchs/base.py
> +        if zoned_dev:
> Why did `is_dev_zoned(path) not work?
get_nvme_drive_capacity_gb() is invoked from the Report() method in fio_zone_writes.py script. The function arg 'path' in this case is actually the path of the results o/p folder (zbdbench_results/xxx).  The func arg for is_dev_zoned() is the sysfs device path which is not available from the Report() method. Hence the change to remove the use of is_dev_zoned() in the routine get_nvme_drive_capacity_gb() - to get it working in this context.

2022-10-12 14:22 UTC, metaspace commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
In CI we run `zbdbench` inside a container. We run it with `--device=/dev/$DEVICE`, and `--security-opt unmask=/sys/dev/block`. Because we need access to the device file for the drive we are targeting and we use sysfs to check zoned properties and size.

Can you try that?

2022-10-13 16:17 UTC, indraneel-m commented on benchs/base.py
> +        return f"podman run --privileged -v \"{dev}:{dev}\" -v \"{self.output}:/output\" {extra_params}"
Tried with the option suggested by Andreas Hindborg. The original FIO scripts work fine. But the new SPDK support that I'm adding does not work. Having issues with sysfs being RO, lsblk failure and another error(PA<->VA related, didn't dig into it)... Basically the preparatory setup.sh spdk script fails followed by spdk launch failing.. The --privileged option seems useful for spdk....

2023-06-23 10:21 UTC, indraneel-m commented
Closing the PR as 1st & 3rd commit are upstreamed as part of Dennis's commit and 2nd commit will be reviewed as part of SPDK support in zbdbench patch set.

2023-06-23 10:21 UTC, closed without merging